version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
    environment:
      - "POSTGRES_USER=Niket"
      - "POSTGRES_PASSWORD=pass123"
    ports:
      - "5432:5432"